### PR TITLE
Update series.ts

### PR DESCRIPTION
**Pull request by maxah**
Capability to handle 'timestamp' instead of formatted date string.

### CODE REVIEW

**Review by hardikbeladiya — APPROVED** [review]
LGTM

**Comment by hardikbeladiya** [comment]
Basically, it will parse the timeStamp (Number) to Date. so I think this PR is Valid

**Comment by ashleydavis** [comment]
Sorry I never noticed this before!

Is it possible to add some tests that exercise this new code?

**Comment by maxah** [comment]
https://codepen.io/maxah-the-selector/pen/BaVdMOQ

**Comment by maxah** [comment]
If a numeric value can be extracted from a text value, it can be converted to Date, I used to process timestamp directly.

**Comment by ashleydavis** [comment]
I'd like to see automated tests added to the code before I merge.

**Comment by ashleydavis** [comment]
Closing because this is old and doesn't come with any automated tests.

**Pull request closed without merging**
