### PR TITLE
Add rollup for esm bundling

### LINKED ISSUE #33: include a ES Module build
Please include a ES Module version of the package so users using bundlers like webpack can benefit from it and get features like tree-shaking, etc.
Right now the package size is quite [high](https://bundlephobia.com/result?p=data-forge@1.6.7)

### PR DESCRIPTION
**Pull request by laevilgenius**
Resolves #33.

### CODE REVIEW

**Comment by ashleydavis** [comment]
Thanks so much. Testing now, will publish a new build in the next few days.

**Comment by ashleydavis** [comment]
@laevilgenius unfortunately I have discovered an issue with this pull request.

I published Data-Forge 1.7.0 with your changes and it causes a problem for both the JavaScript and TypesScript package tests.

When running the js package-test I get the following issue:

```
> npm start

> npm-package-test@ start C:\projects\github\data-forge\data-forge-examples-and-tests\package-test\npm\js
> node index.js

C:\projects\github\data-forge\data-forge-examples-and-tests\package-test\npm\js\node_modules\dayjs\esm\index.js:1
(function (exports, require, module, __filename, __dirname) { import * as C from './constant';
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! npm-package-test@ start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the npm-package-test@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ash\AppData\Local\Temp\dfntmp\npm-cache\_logs\2019-04-30T04_49_28_424Z-debug.log

```

There's a similar issue for the ts package test.

You can find the package test code here:

https://github.com/data-forge/data-forge-examples-and-tests/tree/master/package-test/npm/js

I will have to roll this PR back for the moment and publish 1.7.1 to fix the problem.

If you are able to help me solve the problem was can publish again later.

**Comment by laevilgenius** [comment]
@ashleydavis can you try #38? It should be working now.

**Comment by ashleydavis** [comment]
Thanks so much, I'll look it as soon as I get a chance.

**Pull request merged**
