### PR TITLE
Added JSON5 support

### LINKED ISSUE #42: JSON5 file / JSON object support
Would it be possible for this package to support `.json5` files?
I'm trying to use DF on a JSON5 file but even tho I already have a module that turns that file to a JSON object, there's no way for me to use this package to read either the file or read from the object.
Sticking to JSON isn't an option (as comments are needed).

A workaround would be to save the JSON object to a JSON file and read it again but I'm trying to minimise I/O operations and resources used, so it's not a good option.

### PR DESCRIPTION
**Pull request by Berkmann18**
Resolve #42

### CODE REVIEW

**Comment by ashleydavis** [comment]
Thanks for your contribution. Does this have any effect on regular JSON support?

**Comment by Berkmann18** [comment]
@ashleydavis No, the regular JSON files are read the same way (the only difference is that JSON5 is more lenient when it comes to trailing comas, single quotes and anything that JSON5 adds to the spec).

**Comment by ashleydavis** [comment]
You have replaced JSON.parse with JSON5.parse. This probably isn't the best thing because JSON5.parse has a custom implementation and we don't know how good the performance is. I know that the builtin JSON.parse is really highly optimized.

Would it be possible for you to create a separate fromJSON5 function?

Also to balance it out please provide a toJSON5 function as well.

Thanks for your help on this.

**Comment by Berkmann18** [comment]
Okay, I've done that.

**Comment by ashleydavis** [comment]
That's merged. Thanks so much for your contribution.

**Pull request merged**
